AWSTemplateFormatVersion: '2010-09-09'
Description: 'Billing Alarm Sample'

Parameters:
  AlarmThreshold:
    Type: string
    Default: "50"
  BillingAlarmNotification:
    Type: string
    Default: "Cost threshold has been reached"

Resources:
  SpendingAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription:
        'Fn::Join':
          - ''
          - - Alarm if AWS spending is over $
            - Ref: AlarmThresholdl
      Namespace: AWS/Billing
      MetricName: EstimatedCharges
      Dimensions:
        - Name: Currency
          Value: USD
      Statistic: Maximum
      Period: '21600'
      EvaluationPeriods: '1'
      Threshold:
        Ref: AlarmThreshold
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
      - Ref: BillingAlarmNotification
      InsufficientDataActions:
      - Ref: BillingAlarmNotification